FROM oven/bun:1.3.13-alpine AS app

WORKDIR /app

COPY package.json bun.lock ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json
COPY packages/config/package.json packages/config/package.json
COPY packages/db/package.json packages/db/package.json
COPY packages/domain/package.json packages/domain/package.json

RUN bun install --frozen-lockfile

RUN apk add --no-cache sqlite

COPY . .

ARG VITE_LAB_APP_TITLE
ARG VITE_LAB_SHORT_NAME
ARG VITE_LAB_LAB_NAME
ARG VITE_LAB_INSTITUTION_NAME
ARG VITE_LAB_BASE_URL
ARG VITE_LAB_LOGO_PATH
ARG VITE_LAB_FAVICON_PATH
ARG VITE_LAB_PRIMARY_COLOR
ARG VITE_LAB_TIMEZONE
ARG VITE_LAB_AUTH_EYEBROW
ARG VITE_LAB_AUTH_HEADLINE
ARG VITE_LAB_EMAIL_FROM_NAME
ARG VITE_LAB_EMAIL_FROM_ADDRESS
ARG VITE_LAB_EMAIL_SUPPORT_ADDRESS

ENV VITE_LAB_APP_TITLE=$VITE_LAB_APP_TITLE
ENV VITE_LAB_SHORT_NAME=$VITE_LAB_SHORT_NAME
ENV VITE_LAB_LAB_NAME=$VITE_LAB_LAB_NAME
ENV VITE_LAB_INSTITUTION_NAME=$VITE_LAB_INSTITUTION_NAME
ENV VITE_LAB_BASE_URL=$VITE_LAB_BASE_URL
ENV VITE_LAB_LOGO_PATH=$VITE_LAB_LOGO_PATH
ENV VITE_LAB_FAVICON_PATH=$VITE_LAB_FAVICON_PATH
ENV VITE_LAB_PRIMARY_COLOR=$VITE_LAB_PRIMARY_COLOR
ENV VITE_LAB_TIMEZONE=$VITE_LAB_TIMEZONE
ENV VITE_LAB_AUTH_EYEBROW=$VITE_LAB_AUTH_EYEBROW
ENV VITE_LAB_AUTH_HEADLINE=$VITE_LAB_AUTH_HEADLINE
ENV VITE_LAB_EMAIL_FROM_NAME=$VITE_LAB_EMAIL_FROM_NAME
ENV VITE_LAB_EMAIL_FROM_ADDRESS=$VITE_LAB_EMAIL_FROM_ADDRESS
ENV VITE_LAB_EMAIL_SUPPORT_ADDRESS=$VITE_LAB_EMAIL_SUPPORT_ADDRESS

RUN bun run build
RUN mkdir -p /app/data/backups

ENV NODE_ENV=production
ENV PORT=3001
ENV SERVE_WEB=1
ENV WEB_DIST_DIR=/app/apps/web/dist
ENV DATABASE_URL=file:/app/data/lab.sqlite
ENV BACKUP_DATABASE_PATH=/app/data/lab.sqlite
ENV BACKUP_DIR=/app/data/backups
ENV BACKUP_RETENTION_DAYS=30

EXPOSE 3001

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 CMD bun -e "const r = await fetch('http://127.0.0.1:' + (Bun.env.PORT ?? '3001') + '/health'); if (!r.ok) process.exit(1)"

CMD ["bun", "apps/api/src/index.ts"]
